Replaced aliasInfo, channel delegation and user delagation api calls with sdk call
ethereum-push-notification-service/push-dapp pull request #1019
Opened 2023-04-04 07:12 UTC by deekshithepns

2023-04-06 15:54 UTC, corlard3y reviewed
<img width="1241" alt="Screenshot 2023-04-06 at 16 47 13" src="https://user-images.githubusercontent.com/38462689/230432329-32eee59b-2ab8-4e55-9657-fbf72e7ae35a.png">
Experienced this on the PR, might be another CSS issue specific to the branch, can be resolved with another issue

2023-04-10 11:13 UTC, corlard3y submitted a review, later dismissed

2023-04-12 08:11 UTC, mishramonalisha76 requested changes

2023-04-12 08:13 UTC, deekshithepns commented on src/components/chat/w2wChat/TypeBar/Typebar.tsx
> +  min-height: 25px;
kolade mentioned about that ...

2023-04-12 10:15 UTC, mishramonalisha76 approved these changes

2023-04-13 09:06 UTC, merged