Space widget at bottom
ethereum-push-notification-service/push-dapp pull request #1086
Opened 2023-04-18 05:19 UTC by deekshithepns

2023-04-21 10:14 UTC, abhishek-01k approved these changes

2023-04-24 08:43 UTC, mishramonalisha76 requested changes
The padding for the widget is not  as per figma
Make the widget appear only when we click join space and we are not in that particular space opened.

2023-04-24 08:45 UTC, mishramonalisha76 requested changes

2023-04-24 08:45 UTC, mishramonalisha76 commented on src/components/space/spaceWidget/spaceWidget.tsx
> +  const selectedSpace = spaces[0];
Create a joinedSpaceId in space global context and then it should be set when we click on join space in space box.and then create a const that sould be set as per joinedSpaceId variable from userSpaces from space global context

2023-04-24 08:51 UTC, mishramonalisha76 requested changes

2023-04-24 08:51 UTC, mishramonalisha76 commented on src/components/space/spaceWidget/spaceWidget.tsx
> +                  +190
add it from dummy data

2023-05-05 10:20 UTC, abhishek-01k approved these changes

2023-05-23 10:37 UTC, merged