Space preview component
ethereum-push-notification-service/push-dapp pull request #1093
Opened 2023-04-20 05:41 UTC by deekshithepns

send this kind of link to test preview... http://localhost:3000/chat/spaceid:3e1b3c01ad76a79e998d535111e935bd1bb7d2f5f4cb9ec62ee359e81fdf90b9

2023-04-26 06:41 UTC, abhishek-01k commented on src/components/chat/w2wChat/chats/Chats.tsx
<img width="400" alt="Screenshot 2023-04-26 at 12 09 39 PM" src="https://user-images.githubusercontent.com/77395788/234490531-41dc2540-8b7b-4b14-ba10-8564377893be.png">

Getting this undefined image and description when sending the url in the message link

2023-04-26 06:41 UTC, abhishek-01k commented on src/components/space/spaceReusables/RequestBody.tsx
<img width="466" alt="Screenshot 2023-04-26 at 11 45 48 AM" src="https://user-images.githubusercontent.com/77395788/234485733-3ce96ec3-0c6e-4882-aef3-f8457d804e60.png">

here the time is not showing properly.

2023-04-26 06:42 UTC, abhishek-01k commented on src/components/space/spaceReusables/RequestBody.tsx
Similarly time is not showing properly on the sideBox in Requests section

2023-04-26 06:43 UTC, abhishek-01k reviewed
<img width="889" alt="Screenshot 2023-04-26 at 12 13 03 PM" src="https://user-images.githubusercontent.com/77395788/234491210-276cacb3-2c6d-494c-ba85-be9f79dad2da.png">

Here on the spaceBox padding should be there according to the designs.

2023-04-27 09:21 UTC, abhishek-01k approved these changes

2023-05-01 06:26 UTC, mishramonalisha76 requested changes

2023-05-01 06:26 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/chats/spacePreviewCards/SpacePreviewCard.tsx
> +// React + Web3 Essentials
this file is not used anywhere, can be deleted it

2023-05-01 08:30 UTC, mishramonalisha76 approved these changes

2023-05-01 08:30 UTC, merged