ongoing-video-call-ui-fixes
ethereum-push-notification-service/push-dapp pull request #1141
Opened 2023-05-25 08:53 UTC by samarendra-push

fixes for the issue #1133.

2023-05-29 10:53 UTC, KlausMikhaelson requested changes
<img width="960" alt="image" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/100528412/060bb611-3904-4a97-8259-0943baf4532a">
I'm using a 14 inch laptop and the margin looks 0 here so can you fix that ?

2023-06-02 08:58 UTC, madhur-push commented
@corlard3y ser lets review PR #1141 and merge it then lets review PR #1149, will help us avoid conflicts later.

2023-06-05 09:28 UTC, corlard3y commented
I think this UI does not look right, and i am unable to pick calls too
<img width="1680" alt="Screenshot 2023-06-05 at 10 26 57" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/38462689/0eab0ec5-86f9-4a7f-959f-37a2a765c560">

2023-06-06 09:46 UTC, corlard3y approved these changes

2023-06-06 10:00 UTC, merged