fix:faq section
ethereum-push-notification-service/push-dapp pull request #1351
Opened 2023-12-20 12:59 UTC by route-2

I have added a few extra questions to the docs, in the user section as well as developer section.

2023-12-20 15:27 UTC, HarshRajat requested changes
<img width="1311" alt="Screenshot 2023-12-20 at 7 26 42 PM" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/22663032/53e4eb31-20d6-4479-b29d-544a2383b4d9">

These are outdated as we have unified SDK now, please redo

2023-12-20 15:27 UTC, HarshRajat commented on src/modules/faq/FaqModule.tsx
> +                      Push (EPNS) Documentation for Chat
Should be Video specific

2023-12-20 15:27 UTC, HarshRajat commented on src/modules/faq/FaqModule.tsx
> +                      Push (EPNS) Documentation for Chat
Duplicate, I think you meant spaces over here

2023-12-20 15:27 UTC, HarshRajat commented on src/modules/faq/FaqModule.tsx
> -                  <Span>Sending a notification is possible from the DAPP, Back-end as well as Smart Contracts.</Span>
Rework this to point to the correct documentation at push.org/docs

2024-01-04 13:45 UTC, 0xNilesh approved these changes
just resolved few typos, rest LGTM

2024-01-04 13:46 UTC, merged