Dark mode
ethereum-push-notification-service/push-dapp pull request #1386
Opened 2024-01-16 11:34 UTC by pritipsingh

2024-01-16 12:35 UTC, KlausMikhaelson requested changes

2024-01-16 12:35 UTC, KlausMikhaelson commented on src/components/chat/w2wChat/chatBox/ChatBox.tsx
> +import { ChatProfile, ChatViewList, MessageInput, ChatUIProvider, darkChatTheme, lightChatTheme } from '@pushprotocol/uiweb';
we already have chatuiprovider in chatmodule so why is it added here as well ?

2024-01-17 01:02 UTC, KlausMikhaelson commented on src/components/chat/w2wChat/chatBox/ChatBox.tsx
> +import { ChatProfile, ChatViewList, MessageInput, ChatUIProvider, darkChatTheme, lightChatTheme } from '@pushprotocol/uiweb';
@pritipsingh add it over here instead
https://github.com/ethereum-push-notification-service/push-dapp/blob/4eeebf14e17150770883e66217ca0bfc80ff038a/src/modules/chat/ChatModule.tsx#L351

2024-01-17 06:07 UTC, pritipsingh commented
the changes are pushed
<img width="1070" alt="Screenshot 2024-01-17 at 11 28 13 AM" src="https://github.com/ethereum-push-notification-service/push-dapp/assets/85965351/149c6d02-087e-4ae0-860a-6ca031fc8bff">

2024-01-19 09:59 UTC, merged