Show delegates acc to the delegate chain id
ethereum-push-notification-service/push-dapp pull request #480
Opened 2022-10-13 07:17 UTC by nilesh46

2022-10-17 12:20 UTC, corlard3y submitted a review, later dismissed

2022-10-17 12:58 UTC, mishramonalisha76 requested changes

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/components/DelegateInfo.js
> +import { Image, Item, Span } from "primaries/SharedStyling";
would be better to put comments separating the imports, like other files

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/components/ShowDelegates.jsx
> +const InfoButton = ({ clickHandler, hoverText }) => {
Types for props can be added

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/helpers/CaipHelper.ts
> +export const getCaipToObj = (caip: string) => {
give type for returned varibale for the function

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/helpers/UtilityHelper.ts
> +  isPolygon: (chainId: number) => {
give type for returned varibale for the function

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/helpers/UtilityHelper.ts
> +  isEthereum: (chainId: number) => {
give type for returned varibale for the function

2022-10-17 12:58 UTC, mishramonalisha76 commented on src/components/DelegateInfo.js
> +import { Image, Item, Span } from "primaries/SharedStyling";
We can sperate out imports groups by comments like in other files

2023-01-24 11:50 UTC, 0xNilesh commented
https://github.com/ethereum-push-notification-service/push-storage-node/issues/580

2023-01-24 11:50 UTC, closed without merging