Replaced all occurrences of userShouldBeSearched and its reducer
ethereum-push-notification-service/push-dapp pull request #532
Opened 2022-10-18 10:25 UTC by 0xNilesh

2022-10-18 14:39 UTC, corlard3y approved these changes

2022-10-18 14:41 UTC, corlard3y requested changes
Kindly fix conflicts @0xNilesh

2022-10-18 14:43 UTC, corlard3y approved these changes

2022-10-18 14:55 UTC, mishramonalisha76 requested changes

2022-10-18 14:55 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/newusers/NewUser.tsx
> +    // userShouldBeSearched,
remove these unsused variables here

2022-10-18 14:55 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/searchBar/SearchBar.tsx
> +    // userShouldBeSearched,
remove these unused ones

2022-10-19 11:07 UTC, 0xNilesh commented on src/components/chat/w2wChat/newusers/NewUser.tsx
> +    // userShouldBeSearched,
done

2022-10-19 11:07 UTC, 0xNilesh commented on src/components/chat/w2wChat/searchBar/SearchBar.tsx
> +    // userShouldBeSearched,
done

2022-10-19 11:07 UTC, merged