Created a new function checkingDuplicateMessage for optimising
ethereum-push-notification-service/push-dapp pull request #541
Opened 2022-10-20 11:23 UTC by abhisheksingh-jsdev

Created a new function checkingDuplicateMessage for optimising MessagInCID. This function checks in for duplicateMessage and returns array of Messages

2022-10-24 10:53 UTC, corlard3y requested changes
In the Chats section of this branch, after sending messages - the previous messages dissappear on the UI and I cannot see them. This happens after sending new messages. @abhisheksingh-jsdev

2022-11-17 11:29 UTC, mishramonalisha76 requested changes

2022-11-17 11:29 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/chatBox/ChatBox.tsx
> +  const getMessageIndex = ({newMessages,msgIPFS} : {newMessages:MessageIPFSWithCID[], msgIPFS:MessageIPFSWithCID}): Number=>{
shift these to helper folder

2022-11-17 11:29 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/chatBox/ChatBox.tsx
> +  const getDuplicateMessage = ({messages,msgIPFS} : {messages:MessageIPFSWithCID[], msgIPFS:MessageIPFSWithCID}) : MessageIPFS=>{
can create a common param type for both

2022-11-17 11:29 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/chatBox/ChatBox.tsx
> +  const getMessageIndex = ({newMessages,msgIPFS} : {newMessages:MessageIPFSWithCID[], msgIPFS:MessageIPFSWithCID}): Number=>{
Number type should be number

2022-12-14 13:03 UTC, closed without merging