Remove css files and use shared styling in Chats component
ethereum-push-notification-service/push-dapp pull request #546
Opened 2022-10-21 07:11 UTC by madhurg-epns

2022-10-21 10:30 UTC, corlard3y submitted a review, later dismissed

2022-11-14 09:16 UTC, mishramonalisha76 requested changes
styled.div` here,use shared Styling instead of divs

2022-11-17 12:30 UTC, mishramonalisha76 approved these changes

2022-11-17 12:37 UTC, mishramonalisha76 approved these changes

2022-11-17 12:57 UTC, mishramonalisha76 approved these changes

2022-11-17 13:13 UTC, corlard3y approved these changes

2022-11-17 13:31 UTC, merged