Shifted all the interface types in Chatbox to src/types/Chat.ts
ethereum-push-notification-service/push-dapp pull request #602
Opened 2022-11-10 10:38 UTC by abhisheksingh-jsdev

MessageIPFS, MessageIPFSWithCID, User, ConnectedUser, and Feeds types that are used in PushChat Chatbox.tsx are shifted to src/types/Chat.ts.

2022-11-14 12:58 UTC, corlard3y requested changes
Conflicts on the PR, needs fixing

2022-11-15 11:22 UTC, corlard3y approved these changes

2022-11-15 11:38 UTC, mishramonalisha76 approved these changes

2022-11-15 12:02 UTC, corlard3y approved these changes

2022-11-15 12:31 UTC, merged