channel name bifurcation
ethereum-push-notification-service/push-dapp pull request #619
Opened 2022-11-22 11:08 UTC by deekshithepns

2022-11-23 12:05 UTC, corlard3y submitted a review, later dismissed

2022-11-23 12:19 UTC, mishramonalisha76 requested changes

2022-11-23 12:19 UTC, mishramonalisha76 commented on src/components/ChannelInfo.tsx
> +                console.log(option);
remove console log

2022-11-23 12:19 UTC, mishramonalisha76 commented on src/components/ChannelInfo.tsx
> +          {/* dropdown */}
commented code can be removed

2022-11-23 12:19 UTC, mishramonalisha76 commented on src/components/ChannelInfo.tsx
> +            // placeholder="Your Channel Name"
we can remove this line

2022-11-23 12:19 UTC, mishramonalisha76 commented on src/components/ChannelInfo.tsx
> +              // placeholder="Your Channel Address"
we can remove this line

2022-11-23 12:19 UTC, mishramonalisha76 commented on src/components/ChannelInfo.tsx
> +            // placeholder="Your Channel's Short Description (250 Characters)"
remove this line

2022-11-24 08:20 UTC, mishramonalisha76 approved these changes

2022-11-24 08:26 UTC, merged