Remove Direct Payload on the options when sending manual notification
ethereum-push-notification-service/push-dapp pull request #623
Opened 2022-11-23 09:10 UTC by corlard3y

2022-11-23 12:22 UTC, mishramonalisha76 requested changes
version bump needed

2022-11-23 12:22 UTC, mishramonalisha76 commented on src/components/SendNotifications.tsx
>  const NFTypes = [
Can we add in type for NFTypes.

2022-11-23 12:53 UTC, mishramonalisha76 approved these changes

2022-11-24 09:24 UTC, merged

2022-12-28 04:50 UTC, Tetita commented
g