twitter-preview
ethereum-push-notification-service/push-dapp pull request #651
Opened 2022-12-15 04:54 UTC by deekshithepns

2022-12-19 04:14 UTC, deekshithepns commented
> On sending a tweet link, it keeps showing this loader even if i reload the tab . @deekshithepns <img alt="image" width="612" src="https://user-images.githubusercontent.com/42746736/208058288-bb14082c-967f-43b5-8b18-05cb5fce6257.png">

As I tested again...it is working fine on sender and receiver end... but it is taking some time to load the preview.

2022-12-19 08:55 UTC, corlard3y reviewed
So when i try to copy link from twitter on mobile, it does not work. Only copying the live url on a twitter web app works. It needs to work for both

2022-12-22 11:06 UTC, mishramonalisha76 requested changes

2022-12-23 05:21 UTC, mishramonalisha76 approved these changes

2023-01-05 12:40 UTC, merged