Method 2 for the context problem in the push chat
ethereum-push-notification-service/push-dapp pull request #654
Opened 2022-12-20 05:23 UTC by abhisheksingh-jsdev

Here in this method, I created a separate UserContext.tsx file inside the context folder and added the userContext. By this context we can access getUser function and newUser state.

2023-01-04 08:04 UTC, mishramonalisha76 requested changes

2023-01-04 08:05 UTC, mishramonalisha76 commented on src/pages/ChatPage.tsx
> +const ChatPage = ({getUser,newUser}) => {
Also remove all commented code

2023-01-04 15:22 UTC, abhishek-01k commented on src/pages/ChatPage.tsx
> +const ChatPage = ({getUser,newUser}) => {
This is outdated and is not present in the code

2023-01-16 09:22 UTC, mishramonalisha76 reviewed
LGTM, just remove all commented code

2023-01-18 06:36 UTC, mishramonalisha76 approved these changes

2023-01-19 12:00 UTC, 0xNilesh approved these changes

2023-01-19 12:08 UTC, merged