Add Chain Indicator in Header
ethereum-push-notification-service/push-dapp pull request #658
Opened 2022-12-21 08:16 UTC by madhurg-epns

2023-01-04 12:16 UTC, madhurg-epns commented
@0xNilesh @mishramonalisha76 The design team has given a go ahead to the styling of the Chain Indicator, we can go for the PR review.

2023-01-06 08:18 UTC, mishramonalisha76 commented
@madhurg-epns  

 I guess in tablet view the design needs to be like the mobile version.
<img width="877" alt="image" src="https://user-images.githubusercontent.com/42746736/210957418-0a89a391-55bb-4cde-b66c-7021ba64a176.png">

the dropdown get above the select option's bottom border. In the design in just below the bottom border line.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/42746736/210957477-7488f0c5-976a-4aa2-9dd7-77e422730843.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/42746736/210957728-fdbb3a4d-7bc7-4e62-937f-35dc1977ea99.png">

The icons of the ethereum and polygon chain seems different in figma.

The font weight and font color seems different for the selected option in figma
<img width="304" alt="image" src="https://user-images.githubusercontent.com/42746736/210958401-065cee71-5d79-4e9e-ac53-0aacc78dbbb0.png">


The padding between the icon and the arrow seems lesser in figma and make the border radius of the entire box 19px
<img width="112" alt="image" src="https://user-images.githubusercontent.com/42746736/210959528-e155fd5e-bfa2-4cab-9b91-48b27a9ce716.png">

2023-01-11 08:03 UTC, mishramonalisha76 requested changes

2023-01-11 08:03 UTC, mishramonalisha76 commented on src/components/ChainIndicator.tsx
> +    const chainIds = appConfig.allowedNetworks;
use optional chaining, to avoid undefined cases

2023-01-11 08:03 UTC, mishramonalisha76 commented on src/components/ChainIndicator.tsx
> +const Container = styled.button`
try to use the button from  sharedStyling v2 file

2023-01-11 08:03 UTC, mishramonalisha76 commented on src/components/ChainIndicator.tsx
> +const CurrentChain = styled.span`
try to use the span from sharedStyling v2 file

2023-01-11 08:03 UTC, mishramonalisha76 commented on src/components/Dropdown.tsx
> +const SpanAddress = styled(Span)`
try to use sharedStyling

2023-01-11 12:07 UTC, madhurg-epns commented on src/components/ChainIndicator.tsx
> +  const fetchCurrentChainId = async () => {
@mishramonalisha76 you want me to add types to the useState call right?

2023-01-12 08:26 UTC, mishramonalisha76 submitted a review, later dismissed
LGTM

2023-01-12 08:49 UTC, 0xNilesh approved these changes

2023-01-12 09:03 UTC, 0xNilesh requested changes

2023-01-12 09:03 UTC, 0xNilesh commented on src/components/ChainIndicator.tsx
> +        await window.ethereum.request({
Use library or provider instead of window.ethereum.

2023-01-12 10:24 UTC, 0xNilesh approved these changes

2023-01-12 10:25 UTC, merged