Fixed ENS resolving issues on dev and staging
ethereum-push-notification-service/push-dapp pull request #733
Opened 2023-02-02 07:01 UTC by deekshithepns

2023-02-06 05:41 UTC, mishramonalisha76 requested changes

2023-02-06 05:41 UTC, mishramonalisha76 commented on .vscode/launch.json
> +            "type": "chrome",
any reason for changing this?

2023-02-06 05:41 UTC, mishramonalisha76 commented on src/components/chat/w2wChat/searchBar/SearchBar.tsx
> +        // ens=ethers.utils.getAddress(address.toLowerCase());
remove the commented code

2023-02-06 05:41 UTC, mishramonalisha76 commented on src/hooks/useResolveEns.ts
>  export function useResolveEns(username: string): string {
Can you try with two optional input params, one as address and one as ens, then we can do the jobs for each, as pe which input is provided?

2023-02-06 16:27 UTC, mishramonalisha76 requested changes

2023-02-06 16:27 UTC, mishramonalisha76 commented on .vscode/launch.json
> +            "type": "chrome",
any reason of changing this

2023-02-08 14:27 UTC, 0xNilesh submitted a review, later dismissed

2023-02-08 14:30 UTC, 0xNilesh approved these changes

2023-02-08 14:31 UTC, 0xNilesh approved these changes

2023-02-08 14:32 UTC, mishramonalisha76 approved these changes

2023-02-08 14:32 UTC, merged