added sdk functions for send, start and approve intent
ethereum-push-notification-service/push-dapp pull request #751
Opened 2023-02-08 12:03 UTC by mishramonalisha76

2023-02-09 09:02 UTC, corlard3y requested changes
Unable to send intent for some wallet addresses, not sure what the distinction is. But i keep getting this 'Invalid receiver address' in the console

2023-02-13 12:10 UTC, zaryab2000 commented
Have the requested changes been addressed for this PR yet? 

**Note** - This is a Priority-1 PR @mishramonalisha76 @corlard3y

2023-02-13 12:13 UTC, mishramonalisha76 commented
@zaryab2000 @corlard3y , the fix has to be done from sdk, Shoaib is working on it

2023-02-14 11:30 UTC, corlard3y submitted a review, later dismissed

2023-02-14 11:38 UTC, corlard3y approved these changes

2023-02-14 11:50 UTC, merged